### ISSUE TITLE
slow start

### ISSUE THREAD

**Issue by delanym** [romkatv/gitstatus#241]
Every morning I open a shell and inevitably invoke gitstatus in my workspace, but the first prompt of the day is always much slower. Is there some way to extend whatever caching timeout is going on here?

**Comment by romkatv** [comment]
Which shell are you using?

**Comment by delanym** [comment]
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by romkatv** [comment]
If you keep bash open, gitstatusd closes git repositories after an hour. This is controlled by the following flag:

```text
-r, --repo-ttl-seconds=NUM [default=3600]
 Close git repositories that haven't been used for this long. This is meant to
 release resources such as memory and file descriptors. The next request for a
 repo that's been closed is much slower than for a repo that hasn't been.
 Negative value means infinity.
```

I've just committed https://github.com/romkatv/gitstatus/commit/a9d70ec0d0543e6743299e0b273fd0d48c10cefc that allows you to override the value of this flag when using bash bindings. To do that, you'll need to append `-r -1` to the invocation of `gitstatus_start`. If you are sourcing `gitstatus.prompt.sh`, you'll need to copy that file and modify it (it invokes `gitstatus_start`).

If by "opening a shell" every morning you mean starting bash, then this flag won't help you. When bash starts it starts gitstatusd. This takes time. In addition, the freshly started gitstatusd has empty cache.

Note that none of these problems exist in zsh if you use gitstatus via powerlevel10k or, better yet, via zsh4humans. Prompt is always fast there.

**Comment by delanym** [comment]
Thanks, it does help - i ssh into a tmux session. Ill consider moving back to zsh at some point

**Comment by delanym** [comment]
I modified gitstatus.prompt.sh line `gitstatus_stop && gitstatus_start -s -1 -u -1 -c -1 -d -1 -r -1` and rebooted but the problem persists

**Comment by romkatv** [comment]
Sorry to hear that. I don’t know why it didn’t work out.

**Comment by delanym** [comment]
Ill try -r 100000

Im also getting "warning package.json: No license field" the first time I open the shell

**Comment by romkatv** [comment]
> Ill try -r 100000

This can only make things worse because git repos will close after 100000 seconds (28 hours).

> Im also getting "warning package.json: No license field" the first time I open the shell

This is not coming from gitstatus.

**Comment by delanym** [comment]
Worse in what way? The default is 3600, and Im setting it to 100000, when infinity didn't work at all, no?

**Comment by romkatv** [comment]
Worse in the sense of slower. 27 hours is less than infinity.

The new flag I added can help in the following case:

1. You start bash and `cd` into a git repo.
2. You wait for at least an hour.
3. You press <kbd>Enter</kbd>.

With the default settings on the 3rd step there will be a delay because gitstatusd has closed the git repo and needs to open and scan it again.

However, what you are doing is different as indicated by the warning from yarn. The slowdown in your case either comes from restarting gitstatusd (this is always slow in bash; to mitigate you either need to switch to zsh or stop restarting gitstatusd) or from something else entirely (e.g., from yarn).

**Comment by delanym** [comment]
I understand how the timeout works. I think the bash session that started gitstatusd is closing when I disconnect. I certainly don't restart gitstatus myself. I have this configured in .bashrc

`if [ -f /git/github/gitstatus/gitstatus.prompt.sh ]; then
  . "/git/github/gitstatus/gitstatus.prompt.sh"
fi
`

I assume theres at least one ongoing bash session on my box, but it looks like gitstatus is not detecting existing instances

`ps aux | grep gitstatus`

```
delany     12276  0.0  1.1 5545664 191820 pts/5  Sl+  Jun11   1:24 /home/delany/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.0 --parent-pid=12256 --num-threads=4 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --repo-ttl-seconds=-1
delany    874489  0.0  0.0   3024  1532 pts/0    Sl   08:24   0:00 /home/delany/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.0 --parent-pid=874470 --num-threads=4 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --repo-ttl-seconds=-1
delany    875722  0.0  0.4 1115864 76376 pts/1   Sl+  08:34   0:06 /home/delany/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.1 --parent-pid=875672 --num-threads=4 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --repo-ttl-seconds=-1
delany    875798  0.1  0.4 1115980 77120 pts/2   Sl+  08:34   0:06 /home/delany/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.1 --parent-pid=875778 --num-threads=4 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --repo-ttl-seconds=-1
delany    876005  0.0  0.4 1138812 76836 pts/3   Sl   08:36   0:00 /home/delany/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.1 --parent-pid=875985 --num-threads=4 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --repo-ttl-seconds=-1
delany    884373  0.0  0.0  26376  1776 pts/4    Sl+  10:09   0:00 /home/delany/.cache/gitstatus/gitstatusd-linux-x86_64 -G v1.5.1 --parent-pid=884353 --num-threads=4 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --repo-ttl-seconds=100000
delany    885578  0.0  0.0   9036  2748 pts/3    S+   10:24   0:00 grep --color=auto gitstatus
```

Zsh notwithstanding, have you considered making a systemd service definition?

**Comment by romkatv** [comment]
> I think the bash session that started gitstatusd is closing when I disconnect. I certainly don't restart gitstatus myself. I have this configured in .bashrc

If `.bashrc` gets sourced, it means you are starting bash. When you start bash, gitstatusd starts. Starting gitstatusd from bash is slow. You can either avoid stopping/starting bash (and therefore stopping/starting gitstatusd), or use zsh.

> I assume theres at least one ongoing bash session on my box, but it looks like gitstatus is not detecting existing instances

There is a dedicated gitstatusd for each interactive bash.

> Zsh notwithstanding, have you considered making a systemd service definition?

Yes. Not going to happen because it doesn't seem to be solving any issues and will add a lot of complexity and security concerns.
