### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by abdalrahman-ali** [romkatv/gitstatus#36]
Your git prompt may disappear or become slow.
Run the following command to retry with extra diagnostics:
GITSTATUS_ENABLE_LOGGING=1 gitstatus_start -s 1 -u 1 -d 1 -m -1 POWERLEVEL9K

OUTPUT:

[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.6241.xtrace.A1TYYErcG2 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:8> local os
    +gitstatus_start_impl:8> os=+gitstatus_start_impl:8> uname -s
    +gitstatus_start_impl:8> os=Linux 
    +gitstatus_start_impl:8> [[ -n Linux ]]
    +gitstatus_start_impl:9> [[ Linux != Linux ||+gitstatus_start_impl:9> uname -o
    +gitstatus_start_impl:9> [[ Linux != Linux || GNU/Linux != Android ]]
    +gitstatus_start_impl:10> local arch
    +gitstatus_start_impl:10> arch=+gitstatus_start_impl:10> uname -m
    +gitstatus_start_impl:10> arch=x86_64 
    +gitstatus_start_impl:10> [[ -n x86_64 ]]
    +gitstatus_start_impl:11> local ldd_v
    +gitstatus_start_impl:11> ((  1  ))
    +gitstatus_start_impl:11> ldd_v=+gitstatus_start_impl:11> ldd --version
    +gitstatus_start_impl:11> ldd_v=$'ldd (GNU libc) 2.12\nCopyright (C) 2010 Free Software Foundation, Inc.\nThis is free software; see the source for copying conditions.  There is NO\nwarranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\nWritten by Roland McGrath and Ulrich Drepper.' 
    +gitstatus_start_impl:12> local linkage
    +gitstatus_start_impl:12> [[ Linux != Linux || $'ldd (gnu libc) 2.12\ncopyright (c) 2010 free software foundation, inc.\nthis is free software; see the source for copying conditions.  there is no\nwarranty; not even for merchantability or fitness for a particular purpose.\nwritten by roland mcgrath and ulrich drepper.' == (*glibc*|*gnu\ libc*) ]]
    +gitstatus_start_impl:14> local daemon=/home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64
    +gitstatus_start_impl:15> [[ -f /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 ]]
    +gitstatus_start_impl:17> lock_file=+gitstatus_start_impl:17> mktemp /tmp/gitstatus.6241.lock.XXXXXXXXXX
    +gitstatus_start_impl:17> lock_file=/tmp/gitstatus.6241.lock.SHLkwvnknt 
    +gitstatus_start_impl:18> zsystem flock -f lock_fd /tmp/gitstatus.6241.lock.SHLkwvnknt
    +gitstatus_start_impl:20> req_fifo=+gitstatus_start_impl:20> mktemp -u /tmp/gitstatus.6241.pipe.req.XXXXXXXXXX
    +gitstatus_start_impl:20> req_fifo=/tmp/gitstatus.6241.pipe.req.gsIGfZCIkJ 
    +gitstatus_start_impl:21> mkfifo /tmp/gitstatus.6241.pipe.req.gsIGfZCIkJ
    +gitstatus_start_impl:22> sysopen -rw -o cloexec,sync -u req_fd /tmp/gitstatus.6241.pipe.req.gsIGfZCIkJ
    +gitstatus_start_impl:23> rm -f /tmp/gitstatus.6241.pipe.req.gsIGfZCIkJ
    +gitstatus_start_impl:25> resp_fifo=+gitstatus_start_impl:25> mktemp -u /tmp/gitstatus.6241.pipe.resp.XXXXXXXXXX
    +gitstatus_start_impl:25> resp_fifo=/tmp/gitstatus.6241.pipe.resp.MDvYbf0PdR 
    +gitstatus_start_impl:26> mkfifo /tmp/gitstatus.6241.pipe.resp.MDvYbf0PdR
    +gitstatus_start_impl:27> sysopen -rw -o cloexec -u resp_fd /tmp/gitstatus.6241.pipe.resp.MDvYbf0PdR
    +gitstatus_start_impl:28> rm -f /tmp/gitstatus.6241.pipe.resp.MDvYbf0PdR
    +gitstatus_start_impl:33> zle -F 15 _gitstatus_process_response_POWERLEVEL9K
    +gitstatus_start_impl:35> [[ 1 == 1 ]]
    +gitstatus_start_impl:36> log_file=+gitstatus_start_impl:36> mktemp /tmp/gitstatus.6241.daemon-log.XXXXXXXXXX
    +gitstatus_start_impl:36> log_file=/tmp/gitstatus.6241.daemon-log.kEnSanXUdp 
    +gitstatus_start_impl:38> typeset -g 'GITSTATUS_DAEMON_LOG_POWERLEVEL9K=/tmp/gitstatus.6241.daemon-log.kEnSanXUdp'
    +gitstatus_start_impl:40> local -i threads=0
    +gitstatus_start_impl:41> ((  threads > 0 ))
    +gitstatus_start_impl:42> threads=8 
    +gitstatus_start_impl:43> case Linux (FreeBSD)
    +gitstatus_start_impl:43> case Linux (*)
    +gitstatus_start_impl:45> ((  ! 1  ))
    +gitstatus_start_impl:45> threads=+gitstatus_start_impl:45> getconf _NPROCESSORS_ONLN
    +gitstatus_start_impl:45> threads=16 
    +gitstatus_start_impl:47> ((  threads <= 32  ))
    +gitstatus_start_impl:63> daemon_pid=6505 
    +gitstatus_start_impl:51> zsh -dfxc $'\n      /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64                                     --lock-fd=3                                    --parent-pid=6241                                --num-threads=16                         --max-num-staged=1               --max-num-unstaged=1           --max-num-untracked=1         --dirty-max-index-size=-1\n      echo -nE $\'bye\\x1f0\\x1e\'\n    '
    +gitstatus_start_impl:64> rm -f /tmp/gitstatus.6241.lock.SHLkwvnknt
    +gitstatus_start_impl:66> local reply
    +gitstatus_start_impl:67> echo -nE $'hello\C-_\C-^'
    +gitstatus_start_impl:68> IFS='' +gitstatus_start_impl:68> read -r -d $'\C-^' -u 15 -t 5.0000000000 reply
    +gitstatus_start_impl:69> [[ $'bye\C-_0' == hello0 ]]
                               ^ this command failed

  The content of /tmp/gitstatus.6241.daemon-log.kEnSanXUdp (gitstatus daemon log):

    +zsh:2> /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 '--lock-fd=3' '--parent-pid=6241' '--num-threads=16' '--max-num-staged=1' '--max-num-unstaged=1' '--max-num-untracked=1' '--dirty-max-index-size=-1'
    /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/amursi/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    +zsh:3> echo -nE $'bye\C-_0\C-^'

  Your system information:

    zsh:      5.7.1
    uname -a: Linux orw-amursi-rh6 2.6.32-754.el6.x86_64 #1 SMP Thu May 24 18:18:25 EDT 2018 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
glibc on your system appears to be 9 years old, hence the error.

As a workaround please add the following to your `~/.zshrc`:

```zsh
GITSTATUS_DAEMON=~/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static
```

Let me know if this works for you. If it does, I'll put this issue on hold for some time and will get back to it and implement a proper fix later.

**Comment by romkatv** [comment]
Have you tried my suggestion? Did it help?

**Comment by romkatv** [comment]
I've implemented a proper fix. Once you update powerlevel10k, it should work out of the box. You no longer need to set `GITSTATUS_DAEMON`.

Let me know whether it works for you.

**Comment by runxiong** [comment]
Hi romkatv,

I did git pull in Powerline10k directory and still have this issue.  I tried 
GITSTATUS_DAEMON=~/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static
It worked.

**Comment by runxiong** [comment]
The following is my error message

[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.56642.xtrace.hNGtZG0nP2 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:8> local os
    +gitstatus_start_impl:8> os=+gitstatus_start_impl:8> uname -s
    +gitstatus_start_impl:8> os=Linux
    +gitstatus_start_impl:8> [[ -n Linux ]]
    +gitstatus_start_impl:9> [[ Linux != Linux ||+gitstatus_start_impl:9> uname -o
    +gitstatus_start_impl:9> [[ Linux != Linux || GNU/Linux != Android ]]
    +gitstatus_start_impl:10> local arch
    +gitstatus_start_impl:10> arch=+gitstatus_start_impl:10> uname -m
    +gitstatus_start_impl:10> arch=x86_64
    +gitstatus_start_impl:10> [[ -n x86_64 ]]
    +gitstatus_start_impl:12> local daemon=/local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64
    +gitstatus_start_impl:13> [[ -f /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 ]]
    +gitstatus_start_impl:15> lock_file=+gitstatus_start_impl:15> mktemp /tmp/gitstatus.56642.lock.XXXXXXXXXX
    +gitstatus_start_impl:15> lock_file=/tmp/gitstatus.56642.lock.BUAtW1O1mp
    +gitstatus_start_impl:16> zsystem flock -f lock_fd /tmp/gitstatus.56642.lock.BUAtW1O1mp
    +gitstatus_start_impl:18> req_fifo=+gitstatus_start_impl:18> mktemp -u /tmp/gitstatus.56642.pipe.req.XXXXXXXXXX
    +gitstatus_start_impl:18> req_fifo=/tmp/gitstatus.56642.pipe.req.CDCObCN8vN
    +gitstatus_start_impl:19> mkfifo /tmp/gitstatus.56642.pipe.req.CDCObCN8vN
    +gitstatus_start_impl:20> sysopen -rw -o cloexec,sync -u req_fd /tmp/gitstatus.56642.pipe.req.CDCObCN8vN
    +gitstatus_start_impl:21> rm -f /tmp/gitstatus.56642.pipe.req.CDCObCN8vN
    +gitstatus_start_impl:23> resp_fifo=+gitstatus_start_impl:23> mktemp -u /tmp/gitstatus.56642.pipe.resp.XXXXXXXXXX
    +gitstatus_start_impl:23> resp_fifo=/tmp/gitstatus.56642.pipe.resp.HT9pbZYL5D
    +gitstatus_start_impl:24> mkfifo /tmp/gitstatus.56642.pipe.resp.HT9pbZYL5D
    +gitstatus_start_impl:25> sysopen -rw -o cloexec -u resp_fd /tmp/gitstatus.56642.pipe.resp.HT9pbZYL5D
    +gitstatus_start_impl:26> rm -f /tmp/gitstatus.56642.pipe.resp.HT9pbZYL5D
    +gitstatus_start_impl:31> zle -F 15 _gitstatus_process_response_POWERLEVEL9K
    +gitstatus_start_impl:33> [[ 1 == 1 ]]
    +gitstatus_start_impl:34> log_file=+gitstatus_start_impl:34> mktemp /tmp/gitstatus.56642.daemon-log.XXXXXXXXXX
    +gitstatus_start_impl:34> log_file=/tmp/gitstatus.56642.daemon-log.TWx55urm43
    +gitstatus_start_impl:36> typeset -g 'GITSTATUS_DAEMON_LOG_POWERLEVEL9K=/tmp/gitstatus.56642.daemon-log.TWx55urm43'
    +gitstatus_start_impl:38> local -i threads=0
    +gitstatus_start_impl:39> ((  threads > 0 ))
    +gitstatus_start_impl:40> threads=8
    +gitstatus_start_impl:41> case Linux (FreeBSD)
    +gitstatus_start_impl:41> case Linux (*)
    +gitstatus_start_impl:43> ((  ! 1  ))
    +gitstatus_start_impl:43> threads=+gitstatus_start_impl:43> getconf _NPROCESSORS_ONLN
    +gitstatus_start_impl:43> threads=32
    +gitstatus_start_impl:45> ((  threads <= 32  ))
    +gitstatus_start_impl:48> local -a daemon_args=( '--lock-fd=3' '--parent-pid=56642' '--num-threads=32' '--max-num-staged=99' '--max-num-unstaged=99' '--max-num-untracked=1' '--dirty-max-index-size=-1' )
    +gitstatus_start_impl:66> daemon_pid=58820
    +gitstatus_start_impl:58> zsh -dfxc $'\n      /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=56642 --num-threads=32 --max-num-staged=99 --max-num-unstaged=99 --max-num-untracked=1 --dirty-max-index-size=-1\n      if [[ $? == 127 && -z \'\' && -f /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static ]]; then\n        /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static --lock-fd=3 --parent-pid=56642 --num-threads=32 --max-num-staged=99 --max-num-unstaged=99 --max-num-untracked=1 --dirty-max-index-size=-1\n      fi\n      echo -nE $\'bye\\x1f0\\x1e\'\n    '
    +gitstatus_start_impl:67> rm -f /tmp/gitstatus.56642.lock.BUAtW1O1mp
    +gitstatus_start_impl:69> local reply
    +gitstatus_start_impl:70> echo -nE $'hello\C-_\C-^'
    +gitstatus_start_impl:71> IFS='' +gitstatus_start_impl:71> read -r -d $'\C-^' -u 15 -t 5.0000000000 reply
    +gitstatus_start_impl:72> [[ $'bye\C-_0' == hello0 ]]
                               ^ this command failed

  The content of /tmp/gitstatus.56642.daemon-log.TWx55urm43 (gitstatus daemon log):

    +zsh:2> /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 '--lock-fd=3' '--parent-pid=56642' '--num-threads=32' '--max-num-staged=99' '--max-num-unstaged=99' '--max-num-untracked=1' '--dirty-max-index-size=-1'
    /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    +zsh:3> [[ 1 == 127 ]]
    +zsh:6> echo -nE $'bye\C-_0\C-^'

  Your system information:

    zsh:      5.7.1
    uname -a: Linux dev-dsk-runxiong-2a-f92ce37d.us-west-2.amazon.com 4.9.152-0.1.ac.221.79.329.metal1.x86_64 #1 SMP Thu Mar 14 16:47:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by romkatv** [comment]
These logs are very helpful. My assumption that `ld-linux.so.*` returns 127 if it cannot resolve a dynamic dependency doesn't hold on your system. I've change my code to not rely on this assumption.

Please update powerlevel10k and try again (without defining `GITSTATUS_DAEMON`).

**Comment by runxiong** [comment]
Tried git pull, and without defining GITSTATUS_DAEMON
still have issue, seems same error message

❯  GITSTATUS_ENABLE_LOGGING=1 gitstatus_start -s 99 -u 99 -d 1 -m -1 POWERLEVEL9K
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.116087.xtrace.aD29mZbeY9 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:8> local os
    +gitstatus_start_impl:8> os=+gitstatus_start_impl:8> uname -s
    +gitstatus_start_impl:8> os=Linux
    +gitstatus_start_impl:8> [[ -n Linux ]]
    +gitstatus_start_impl:9> [[ Linux != Linux ||+gitstatus_start_impl:9> uname -o
    +gitstatus_start_impl:9> [[ Linux != Linux || GNU/Linux != Android ]]
    +gitstatus_start_impl:10> local arch
    +gitstatus_start_impl:10> arch=+gitstatus_start_impl:10> uname -m
    +gitstatus_start_impl:10> arch=x86_64
    +gitstatus_start_impl:10> [[ -n x86_64 ]]
    +gitstatus_start_impl:12> local daemon=/local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64
    +gitstatus_start_impl:13> [[ -f /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 ]]
    +gitstatus_start_impl:15> lock_file=+gitstatus_start_impl:15> mktemp /tmp/gitstatus.116087.lock.XXXXXXXXXX
    +gitstatus_start_impl:15> lock_file=/tmp/gitstatus.116087.lock.4KLYFnf5ez
    +gitstatus_start_impl:16> zsystem flock -f lock_fd /tmp/gitstatus.116087.lock.4KLYFnf5ez
    +gitstatus_start_impl:18> req_fifo=+gitstatus_start_impl:18> mktemp -u /tmp/gitstatus.116087.pipe.req.XXXXXXXXXX
    +gitstatus_start_impl:18> req_fifo=/tmp/gitstatus.116087.pipe.req.7QDypawv2I
    +gitstatus_start_impl:19> mkfifo /tmp/gitstatus.116087.pipe.req.7QDypawv2I
    +gitstatus_start_impl:20> sysopen -rw -o cloexec,sync -u req_fd /tmp/gitstatus.116087.pipe.req.7QDypawv2I
    +gitstatus_start_impl:21> rm -f /tmp/gitstatus.116087.pipe.req.7QDypawv2I
    +gitstatus_start_impl:23> resp_fifo=+gitstatus_start_impl:23> mktemp -u /tmp/gitstatus.116087.pipe.resp.XXXXXXXXXX
    +gitstatus_start_impl:23> resp_fifo=/tmp/gitstatus.116087.pipe.resp.zCrKMCKYns
    +gitstatus_start_impl:24> mkfifo /tmp/gitstatus.116087.pipe.resp.zCrKMCKYns
    +gitstatus_start_impl:25> sysopen -rw -o cloexec -u resp_fd /tmp/gitstatus.116087.pipe.resp.zCrKMCKYns
    +gitstatus_start_impl:26> rm -f /tmp/gitstatus.116087.pipe.resp.zCrKMCKYns
    +gitstatus_start_impl:31> zle -F 15 _gitstatus_process_response_POWERLEVEL9K
    +gitstatus_start_impl:33> [[ 1 == 1 ]]
    +gitstatus_start_impl:34> log_file=+gitstatus_start_impl:34> mktemp /tmp/gitstatus.116087.daemon-log.XXXXXXXXXX
    +gitstatus_start_impl:34> log_file=/tmp/gitstatus.116087.daemon-log.b0m0EH6XuQ
    +gitstatus_start_impl:36> typeset -g 'GITSTATUS_DAEMON_LOG_POWERLEVEL9K=/tmp/gitstatus.116087.daemon-log.b0m0EH6XuQ'
    +gitstatus_start_impl:38> local -i threads=0
    +gitstatus_start_impl:39> ((  threads > 0 ))
    +gitstatus_start_impl:40> threads=8
    +gitstatus_start_impl:41> case Linux (FreeBSD)
    +gitstatus_start_impl:41> case Linux (*)
    +gitstatus_start_impl:43> ((  ! 1  ))
    +gitstatus_start_impl:43> threads=+gitstatus_start_impl:43> getconf _NPROCESSORS_ONLN
    +gitstatus_start_impl:43> threads=32
    +gitstatus_start_impl:45> ((  threads <= 32  ))
    +gitstatus_start_impl:48> local -a daemon_args=( '--lock-fd=3' '--parent-pid=116087' '--num-threads=32' '--max-num-staged=99' '--max-num-unstaged=99' '--max-num-untracked=1' '--dirty-max-index-size=-1' )
    +gitstatus_start_impl:66> daemon_pid=116205
    +gitstatus_start_impl:58> zsh -dfxc $'\n      /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 --lock-fd=3 --parent-pid=116087 --num-threads=32 --max-num-staged=99 --max-num-unstaged=99 --max-num-untracked=1 --dirty-max-index-size=-1\n      if [[ $? == 127 && -z \'\' && -f /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static ]]; then\n        /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64-static --lock-fd=3 --parent-pid=116087 --num-threads=32 --max-num-staged=99 --max-num-unstaged=99 --max-num-untracked=1 --dirty-max-index-size=-1\n      fi\n      echo -nE $\'bye\\x1f0\\x1e\'\n    '
    +gitstatus_start_impl:67> rm -f /tmp/gitstatus.116087.lock.4KLYFnf5ez
    +gitstatus_start_impl:69> local reply
    +gitstatus_start_impl:70> echo -nE $'hello\C-_\C-^'
    +gitstatus_start_impl:71> IFS='' +gitstatus_start_impl:71> read -r -d $'\C-^' -u 15 -t 5.0000000000 reply
    +gitstatus_start_impl:72> [[ $'bye\C-_0' == hello0 ]]
                               ^ this command failed

  The content of /tmp/gitstatus.116087.daemon-log.b0m0EH6XuQ (gitstatus daemon log):

    +zsh:2> /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64 '--lock-fd=3' '--parent-pid=116087' '--num-threads=32' '--max-num-staged=99' '--max-num-unstaged=99' '--max-num-untracked=1' '--dirty-max-index-size=-1'
    /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /local/home/runxiong/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64)
    +zsh:3> [[ 1 == 127 ]]
    +zsh:6> echo -nE $'bye\C-_0\C-^'

  Your system information:

    zsh:      5.7.1
    uname -a: Linux dev-dsk-runxiong-2a-f92ce37d.us-west-2.amazon.com 4.9.152-0.1.ac.221.79.329.metal1.x86_64 #1 SMP Thu Mar 14 16:47:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
I see from the logs that you aren't using the newest version of powerlevel10k. Either `git pull` didn't work or your have more than one version of powerlevel10k cloned and accidentally using the wrong one.

To be sure you are using the right version, remove all powerlevel10k directories you have and then `git clone` again.

**Comment by runxiong** [comment]
worked, thanks.

**Comment by romkatv** [comment]
Thanks for verifying and for reporting the issue in the first place.
